spring:
  application:
    name: moasis-sherlock
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /docs