spring:
  application:
    name: moasis-sherlock
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /docs


